package com.university.universityapplication.constans.postgres_constants.postgres_index_constants;

public enum PostgresIndexesNames {
    UNIVERSITY_TEACHERS_NAME_INDEX,
    UNIVERSITY_TEACHERS_EMAIL_INDEX,

    UNIVERSITY_STUDENTS_NAME_INDEX,
    UNIVERSITY_STUDENTS_EMAIL_INDEX,

    UNIVERSITY_STUDENTS_MARKS_INDEX,
    UNIVERSITY_STUDENT_MARKS_STUDENT_AND_TEACHER_REF_INDEX,

    UNIVERSITY_GROUPS_GROUP_NAME_INDEX,

    UNIVERSITY_COMMENT_MARK_INDEX,

    UNIVERSITY_LESSON_LESSON_NAME_INDEX,
    UNIVERSITY_LESSON_LESSON_STATUS_INDEX,

    UNIVERSITY_STUDENT_APPEARANCE_IN_LESSONS_TYPES_INDEX,
}
